import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Locale, i18n } from "@/i18n-config";
import { Header } from "@/components/header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  params: { lang: Locale };
  children: React.ReactNode;
}>;

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  params: { lang },
  children,
}: RootLayoutProps) {
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Header lang={lang} />
        <main className="px-4">{children}</main>
      </body>
    </html>
  );
}
